//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginSingUp
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mobile_Number { get; set; }
        public string Email_Address { get; set; }
        public string password { get; set; }
        public string User_Identity { get; set; }
        public string ConfirmPassword { get; set; }
        public string NewPassword { get; set; }
    }
}
