//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StplEntities : DbContext
    {
        public StplEntities()
            : base("name=StplEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Srm> Srms { get; set; }
        public virtual DbSet<Multicheckbox> Multicheckboxes { get; set; }
        public virtual DbSet<LoginSingUp> LoginSingUps { get; set; }
        public virtual DbSet<CountryName> CountryNames { get; set; }
        public virtual DbSet<StateName> StateNames { get; set; }
        public virtual DbSet<ForgetPassword_Tbl> ForgetPassword_Tbl { get; set; }
    
        public virtual ObjectResult<SelectDataFinally_Result> SelectDataFinally()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectDataFinally_Result>("SelectDataFinally");
        }
    }
}
